// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * Generates src/shared/i18n/catalogs.generated.ts, the Worker's index of all
 * translation files (§7.5). The web app uses Vite's import.meta.glob instead;
 * wrangler's bundler has no glob imports, hence this generated file.
 *
 * Adding a language = dropping <locale>.json next to en.json. This script runs
 * before dev/build/test/typecheck, so no code changes are needed.
 */
import { readdirSync } from 'node:fs';
import { join } from 'node:path';

const dir = join(import.meta.dir, '..', 'src', 'shared', 'i18n');
const locales = readdirSync(dir)
  .filter((f) => /^[a-z]{2,3}(-[A-Za-z0-9]+)*\.json$/.test(f))
  .map((f) => f.replace(/\.json$/, ''))
  .sort();

const ident = (l: string) => `l_${l.replace(/-/g, '_')}`;
const out = [
  '// GENERATED by scripts/i18n-index.ts. Do not edit; not committed.',
  "import type { Catalogs } from './translate';",
  ...locales.map((l) => `import ${ident(l)} from './${l}.json';`),
  '',
  `export const catalogs = {\n${locales.map((l) => `  '${l}': ${ident(l)},`).join('\n')}\n} as unknown as Catalogs;`,
  '',
].join('\n');

await Bun.write(join(dir, 'catalogs.generated.ts'), out);
console.log(`i18n index: ${locales.join(', ')}`);
